pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'Primal'

include(
        'mods:core',
        'mods:progression',
        'mods:actions',
        'mods:society',
        'mods:settlement',
        'mods:warfare'
)
